window.SCIENTIFIC_SPANISH_MAP = {
  "Abroscopus albogularis": "Mosquitero carirrufo",
  "Abroscopus schisticeps": "Mosquitero carinegro",
  "Abroscopus superciliaris": "Mosquitero cejiblanco",
  "Acanthis flammea": "Pardillo norteño",
  "Accipiter nisus": "Gavilán común",
  "Aceros nipalensis": "Cálao del Nepal",
  "Acridotheres albocinctus": "Miná acollarado",
  "Acridotheres burmannicus": "Miná birmano",
  "Acridotheres cristatellus": "Miná crestado",
  "Acridotheres grandis": "Miná grande",
  "Acridotheres tristis": "Miná común",
  "Acrocephalus agricola": "Carricero agrícola",
  "Acrocephalus arundinaceus": "Carricero tordal",
  "Acrocephalus bistrigiceps": "Carricerín cejinegro",
  "Acrocephalus concinens": "Carricero de Swinhoe",
  "Acrocephalus dumetorum": "Carricero de Blyth",
  "Acrocephalus melanopogon": "Carricerín real",
  "Acrocephalus orientalis": "Carricero oriental",
  "Acrocephalus schoenobaenus": "Carricerín común",
  "Acrocephalus scirpaceus": "Carricero común",
  "Acrocephalus sorghophilus": "Carricerín estriado",
  "Acrocephalus stentoreus": "Carricero estentóreo",
  "Acrocephalus tangorum": "Carricerín manchú",
  "Actinodura cyanouroptera": "Siva aliazul",
  "Actinodura egertoni": "Sibia de Egerton",
  "Actinodura morrisoniana": "Sibia de Formosa",
  "Actinodura nipalensis": "Sibia nepalesa",
  "Actinodura ramsayi": "Sibia de anteojos occidental",
  "Actinodura souliei": "Sibia de Tonkín",
  "Actinodura strigula": "Minla colicastaña",
  "Actinodura waldeni": "Sibia de Yunnan",
  "Actitis hypoleucos": "Andarríos chico",
  "Aegithalos bonvaloti": "Mito cejinegro",
  "Aegithalos caudatus": "Mito común",
  "Aegithalos concinnus": "Mito gorjinegro común",
  "Aegithalos fuliginosus": "Mito cuelliblanco",
  "Aegithalos glaucogularis": "Mito gorjigrís",
  "Aegithalos iouschistos": "Mito frentirrufo",
  "Aegithina lafresnayei": "Iora grande",
  "Aegithina tiphia": "Iora común",
  "Aegolius funereus": "Mochuelo boreal",
  "Aegypius monachus": "Buitre negro",
  "Aerodramus brevirostris": "Salangana del Himalaya",
  "Aerodramus fuciphagus": "Salangana nidoblanco",
  "Aethopyga christinae": "Suimanga de Christina",
  "Aethopyga gouldiae": "Suimanga de Gould",
  "Aethopyga ignicauda": "Suimanga colafuego",
  "Aethopyga nipalensis": "Suimanga coliverde",
  "Aethopyga saturata": "Suimanga gorjinegro",
  "Aethopyga siparaja": "Suimanga siparaja",
  "Agraphospiza rubescens": "Camachuelo de Blanford",
  "Agropsar philippensis": "Estornino carirrojo",
  "Agropsar sturninus": "Estornino dáurico",
  "Aix galericulata": "Pato mandarín",
  "Alauda arvensis": "Alondra común",
  "Alauda gulgula": "Alondra oriental",
  "Alauda leucoptera": "Calandria aliblanca",
  "Alaudala cheleensis": "Terrera de Mongolia",
  "Alaudala heinei": "Terrera pálida",
  "Alcedo atthis": "Martín pescador común",
  "Alcedo hercules": "Martín pescador hércules",
  "Alcedo meninting": "Martín pescador meninting",
  "Alcippe davidi": "Fulveta de David",
  "Alcippe fratercula": "Fulveta de Yunnan",
  "Alcippe hueti": "Fulveta de Huet",
  "Alcippe morrisonia": "Fulveta carigrís",
  "Alcippe nipalensis": "Fulveta nepalesa",
  "Alcippe poioicephala": "Fulveta cariparda",
  "Alcurus striatus": "Bulbul estriado",
  "Alectoris chukar": "Perdiz chúcar",
  "Alectoris magna": "Perdiz magna",
  "Alophoixus flaveolus": "Bulbul frentigrís",
  "Alophoixus pallidus": "Bulbul pálido",
  "Amandava amandava": "Bengalí rojo",
  "Amaurornis phoenicurus": "Gallineta pechiblanca",
  "Ampeliceps coronatus": "Miná coronado",
  "Anarhynchus alexandrinus": "Chorlitejo patinegro",
  "Anarhynchus asiaticus": "Chorlitejo asiático chico",
  "Anarhynchus dealbatus": "Chorlitejo cariblanco",
  "Anarhynchus leschenaultii": "Chorlitejo mongol grande",
  "Anarhynchus mongolus": "Chorlitejo mongol chico",
  "Anarhynchus veredus": "Chorlito asiático grande",
  "Anas acuta": "Ánade rabudo norteño",
  "Anas carolinensis": "Cerceta americana",
  "Anas crecca": "Cerceta común",
  "Anas luzonica": "Ánade filipino",
  "Anas platyrhynchos": "Ánade azulón",
  "Anas poecilorhyncha": "Ánade picopinto indio",
  "Anas zonorhyncha": "Ánade picopinto chino",
  "Anastomus oscitans": "Picotenaza asiático",
  "Anhinga melanogaster": "Anhinga asiática",
  "Anorrhinus austeni": "Cálao pardo de Austen",
  "Anous minutus": "Tiñosa menuda",
  "Anous stolidus": "Tiñosa boba",
  "Anser albifrons": "Ánsar careto",
  "Anser anser": "Ánsar común",
  "Anser caerulescens": "Ánsar nival",
  "Anser cygnoides": "Ánsar cisnal",
  "Anser erythropus": "Ánsar chico",
  "Anser fabalis": "Ánsar campestre",
  "Anser indicus": "Ánsar indio",
  "Anser serrirostris": "Ánsar campestre de la tundra",
  "Anthipes monileger": "Papamoscas gargantilla",
  "Anthracoceros albirostris": "Cálao cariblanco",
  "Anthreptes malacensis": "Suimanga gorjipardo",
  "Anthus campestris": "Bisbita campestre",
  "Anthus cervinus": "Bisbita gorjirrojo",
  "Anthus godlewskii": "Bisbita estepario",
  "Anthus gustavi": "Bisbita del Pechora",
  "Anthus hodgsoni": "Bisbita de Hodgson",
  "Anthus pratensis": "Bisbita pratense",
  "Anthus richardi": "Bisbita de Richard",
  "Anthus roseatus": "Bisbita rosado",
  "Anthus rufulus": "Bisbita oriental",
  "Anthus spinoletta": "Bisbita alpino",
  "Anthus sylvanus": "Bisbita del Himalaya",
  "Anthus trivialis": "Bisbita arbóreo",
  "Antigone antigone": "Grulla sarus",
  "Antigone canadensis": "Grulla canadiense",
  "Antigone vipio": "Grulla cuelliblanca",
  "Aplonis panayensis": "Estornino bronceado",
  "Apus acuticauda": "Vencejo de los Khasi",
  "Apus apus": "Vencejo común",
  "Apus cooki": "Vencejo de Tailandia",
  "Apus nipalensis": "Vencejo oriental",
  "Apus pacificus": "Vencejo del Pacífico",
  "Aquila chrysaetos": "Águila real",
  "Aquila fasciata": "Águila perdicera",
  "Aquila heliaca": "Águila imperial oriental",
  "Aquila nipalensis": "Águila esteparia",
  "Arachnothera longirostra": "Arañero chico",
  "Arachnothera magna": "Arañero estriado",
  "Arborophila ardens": "Arborófila de Hainán",
  "Arborophila atrogularis": "Arborófila cariblanca",
  "Arborophila brunneopectus": "Arborófila pechiparda",
  "Arborophila crudigularis": "Arborófila de Formosa",
  "Arborophila gingica": "Arborófila de Fujián",
  "Arborophila mandellii": "Arborófila pechirroja",
  "Arborophila rufipectus": "Arborófila de Sichuán",
  "Arborophila rufogularis": "Arborófila golirrufa",
  "Arborophila torqueola": "Arborófila común",
  "Ardea alba": "Garceta grande",
  "Ardea cinerea": "Garza real",
  "Ardea coromanda": "Garcilla bueyera oriental",
  "Ardea insignis": "Garza ventriblanca",
  "Ardea intermedia": "Garceta intermedia",
  "Ardea purpurea": "Garza imperial",
  "Ardenna carneipes": "Pardela paticlara",
  "Ardenna grisea": "Pardela sombría",
  "Ardenna pacifica": "Pardela del Pacífico",
  "Ardenna tenuirostris": "Pardela de Tasmania",
  "Ardeola bacchus": "Garcilla china",
  "Ardeola grayii": "Garcilla india",
  "Ardeola speciosa": "Garcilla indonesia",
  "Arenaria interpres": "Vuelvepiedras común",
  "Artamus fuscus": "Artamo ceniciento",
  "Arundinax aedon": "Carricero picogordo",
  "Asarcornis scutulata": "Pato de jungla",
  "Asio flammeus": "Búho campestre",
  "Asio otus": "Búho chico",
  "Astur gentilis": "Azor común",
  "Athene brama": "Mochuelo brahmán",
  "Athene noctua": "Mochuelo europeo",
  "Aviceda jerdoni": "Baza oriental",
  "Aviceda leuphotes": "Baza negro",
  "Aythya affinis": "Porrón bola",
  "Aythya baeri": "Porrón de Baer",
  "Aythya collaris": "Porrón acollarado",
  "Aythya ferina": "Porrón europeo",
  "Aythya fuligula": "Porrón moñudo",
  "Aythya marila": "Porrón bastardo",
  "Aythya nyroca": "Porrón pardo",
  "Aythya valisineria": "Porrón coacoxtle",
  "Bambusicola fytchii": "Bambusícola montana",
  "Bambusicola sonorivox": "Bambusícola de Formosa",
  "Bambusicola thoracicus": "Bambusícola china",
  "Batrachostomus hodgsoni": "Podargo colilargo",
  "Blythipicus pyrrhotis": "Pito orejirrojo",
  "Bombycilla garrulus": "Ampelis europeo",
  "Bombycilla japonica": "Ampelis japonés",
  "Botaurus cinnamomeus": "Avetorillo canelo",
  "Botaurus eurhythmus": "Avetorillo manchú",
  "Botaurus flavicollis": "Avetorillo negro",
  "Botaurus minutus": "Avetorillo común",
  "Botaurus sinensis": "Avetorillo chino",
  "Botaurus stellaris": "Avetoro común",
  "Brachypteryx cruralis": "Alicorto del Himalaya",
  "Brachypteryx goodfellowi": "Alicorto de Formosa",
  "Brachypteryx hyperythra": "Alicorto ventrirrufo",
  "Brachypteryx leucophris": "Alicorto chico",
  "Brachypteryx sinensis": "Alicorto chino",
  "Brachyramphus perdix": "Mérgulo jaspeado asiático",
  "Branta bernicla": "Barnacla carinegra",
  "Branta canadensis": "Barnacla canadiense grande",
  "Branta hutchinsii": "Barnacla canadiense chica",
  "Branta leucopsis": "Barnacla cariblanca",
  "Branta ruficollis": "Barnacla cuelliroja",
  "Bubo bubo": "Búho real",
  "Bubo scandiacus": "Búho nival",
  "Bucanetes mongolicus": "Camachuelo mongol",
  "Bucephala clangula": "Porrón osculado",
  "Buceros bicornis": "Cálao bicorne",
  "Bulweria bulwerii": "Petrel de Bulwer",
  "Burhinus oedicnemus": "Alcaraván común",
  "Butastur indicus": "Busardo carigrís",
  "Butastur liventer": "Busardo alirrufo",
  "Butastur teesa": "Busardo tisa",
  "Buteo buteo": "Busardo ratonero",
  "Buteo hemilasius": "Busardo mongol",
  "Buteo japonicus": "Busardo japonés",
  "Buteo lagopus": "Busardo calzado",
  "Buteo refectus": "Busardo del Himalaya",
  "Buteo rufinus": "Busardo moro",
  "Butorides striata": "Garcita verdosa",
  "Cacomantis merulinus": "Cuco plañidero",
  "Cacomantis sonneratii": "Cuco bayo",
  "Calandrella acutirostris": "Terrera de Hume",
  "Calandrella brachydactyla": "Terrera común",
  "Calandrella dukhunensis": "Terrera oriental",
  "Calcarius lapponicus": "Escribano lapón",
  "Calidris acuminata": "Correlimos acuminado",
  "Calidris alba": "Correlimos tridáctilo",
  "Calidris alpina": "Correlimos común",
  "Calidris bairdii": "Correlimos de Baird",
  "Calidris canutus": "Correlimos gordo",
  "Calidris falcinellus": "Correlimos falcinelo",
  "Calidris ferruginea": "Correlimos zarapitín",
  "Calidris fuscicollis": "Correlimos culiblanco",
  "Calidris himantopus": "Correlimos zancolín",
  "Calidris mauri": "Correlimos de Alaska",
  "Calidris melanotos": "Correlimos pectoral",
  "Calidris minuta": "Correlimos menudo",
  "Calidris ptilocnemis": "Correlimos roquero",
  "Calidris pugnax": "Combatiente",
  "Calidris pygmaea": "Correlimos cuchareta",
  "Calidris ruficollis": "Correlimos cuellirrojo",
  "Calidris subminuta": "Correlimos dedilargo",
  "Calidris subruficollis": "Correlimos canelo",
  "Calidris temminckii": "Correlimos de Temminck",
  "Calidris tenuirostris": "Correlimos grande",
  "Callacanthis burtoni": "Pinzón de anteojos",
  "Calliope calliope": "Ruiseñor calíope",
  "Calliope obscura": "Ruiseñor gorjinegro",
  "Calliope pectardens": "Ruiseñor de David",
  "Calliope pectoralis": "Ruiseñor pechinegro del Himalaya",
  "Calliope tschebaiewi": "Ruiseñor pechinegro chino",
  "Calonectris leucomelas": "Pardela canosa",
  "Caprimulgus aegyptius": "Chotacabras egipcio",
  "Caprimulgus affinis": "Chotacabras de sabana",
  "Caprimulgus europaeus": "Chotacabras europeo",
  "Caprimulgus jotaka": "Chotacabras jotaka",
  "Caprimulgus macrurus": "Chotacabras macruro",
  "Carduelis carduelis": "Jilguero europeo",
  "Carpodacus davidianus": "Camachuelo bonito chino",
  "Carpodacus dubius": "Camachuelo chino",
  "Carpodacus edwardsii": "Camachuelo de Edwards",
  "Carpodacus erythrinus": "Camachuelo carminoso",
  "Carpodacus formosanus": "Camachuelo de Formosa",
  "Carpodacus grandis": "Camachuelo de Blyth",
  "Carpodacus pulcherrimus": "Camachuelo bonito del Himalaya",
  "Carpodacus puniceus": "Camachuelo frentirrojo",
  "Carpodacus rhodochlamys": "Camachuelo dorsirrojo",
  "Carpodacus roborowskii": "Camachuelo de Roborowski",
  "Carpodacus rodochroa": "Camachuelo cejirrosado",
  "Carpodacus rodopeplus": "Camachuelo alimoteado",
  "Carpodacus roseus": "Camachuelo de Pallas",
  "Carpodacus rubicilla": "Camachuelo grande",
  "Carpodacus rubicilloides": "Camachuelo estriado",
  "Carpodacus sibiricus": "Camachuelo colilargo",
  "Carpodacus sillemi": "Pinzón montano de Sillem",
  "Carpodacus sipahi": "Camachuelo escarlata",
  "Carpodacus stoliczkae": "Camachuelo pálido",
  "Carpodacus subhimachalus": "Camachuelo cejirrojo",
  "Carpodacus thura": "Camachuelo de Thura",
  "Carpodacus trifasciatus": "Camachuelo tribarrado",
  "Carpodacus verreauxii": "Camachuelo de Sharpe",
  "Carpodacus vinaceus": "Camachuelo vinoso",
  "Carpodacus waltoni": "Camachuelo culirrosado",
  "Cecropis daurica": "Golondrina dáurica",
  "Centropus bengalensis": "Cucal bengalí",
  "Centropus sinensis": "Cucal chino",
  "Cephalopyrus flammiceps": "Pájaro moscón carirrojo",
  "Cercotrichas galactotes": "Alzacola rojizo",
  "Cerorhinca monocerata": "Alca unicórnea",
  "Certhia discolor": "Agateador gorjipardo",
  "Certhia familiaris": "Agateador euroasiático",
  "Certhia himalayana": "Agateador del Himalaya",
  "Certhia hodgsoni": "Agateador de Hodgson",
  "Certhia manipurensis": "Agateador de Manipur",
  "Certhia nipalensis": "Agateador nepalés",
  "Certhia tianquanensis": "Agateador de Sichuan",
  "Ceryle rudis": "Martín pescador pío",
  "Cettia brunnifrons": "Cetia capirotada",
  "Cettia castaneocoronata": "Cetia cabecicastaña",
  "Cettia cetti": "Cetia ruiseñor",
  "Cettia major": "Cetia grande",
  "Ceyx erithaca": "Martín pigmeo oriental",
  "Chalcoparia singalensis": "Suimanga carirrubí",
  "Chalcophaps indica": "Palomita esmeralda cabecigrís",
  "Charadrius hiaticula": "Chorlitejo grande",
  "Chelidorhynx hypoxanthus": "Papamoscas ventrigualdo",
  "Chlamydotis macqueenii": "Avutarda hubara asiática",
  "Chlidonias hybrida": "Fumarel cariblanco",
  "Chlidonias leucopterus": "Fumarel aliblanco",
  "Chlidonias niger": "Fumarel común",
  "Chloris ambigua": "Verderón cabecinegro",
  "Chloris chloris": "Verderón común",
  "Chloris sinica": "Verderón chino",
  "Chloris spinoides": "Verderón del Himalaya",
  "Chloropsis aurifrons": "Verdín frentidorado",
  "Chloropsis hardwickii": "Verdín ventrinaranja occidental",
  "Chloropsis moluccensis": "Verdín aliazul",
  "Chroicocephalus brunnicephalus": "Gaviota centroasiática",
  "Chroicocephalus genei": "Gaviota picofina",
  "Chroicocephalus novaehollandiae": "Gaviota plateada australiana",
  "Chroicocephalus ridibundus": "Gaviota reidora",
  "Chrysococcyx maculatus": "Cuclillo esmeralda asiático",
  "Chrysococcyx xanthorhynchus": "Cuclillo violeta",
  "Chrysocolaptes guttacristatus": "Pito sultán grande",
  "Chrysolophus amherstiae": "Faisán de Lady Amherst",
  "Chrysolophus pictus": "Faisán dorado",
  "Chrysomma sinense": "Timalí ojigualdo",
  "Chrysophlegma flavinucha": "Pito nuquigualdo",
  "Ciconia boyciana": "Cigüeña oriental",
  "Ciconia ciconia": "Cigüeña blanca",
  "Ciconia episcopus": "Cigüeña lanuda asiática",
  "Ciconia nigra": "Cigüeña negra",
  "Cinclidium frontale": "Ruiseñor frentiazul",
  "Cinclus cinclus": "Mirlo acuático europeo",
  "Cinclus pallasii": "Mirlo acuático pardo",
  "Cinnyris asiaticus": "Suimanga asiático",
  "Cinnyris jugularis": "Suimanga dorsioliva",
  "Circaetus gallicus": "Culebrera europea",
  "Circus aeruginosus": "Aguilucho lagunero occidental",
  "Circus cyaneus": "Aguilucho pálido",
  "Circus macrourus": "Aguilucho papialbo",
  "Circus melanoleucos": "Aguilucho pío",
  "Circus pygargus": "Aguilucho cenizo",
  "Circus spilonotus": "Aguilucho lagunero oriental",
  "Cissa chinensis": "Urraca verde",
  "Cissa hypoleuca": "Urraca ventrigualda",
  "Cisticola exilis": "Cistícola cabecidorado",
  "Cisticola juncidis": "Cistícola buitrón",
  "Clamator coromandus": "Críalo oriental",
  "Clamator jacobinus": "Críalo blanquinegro",
  "Clanga clanga": "Águila moteada",
  "Clangula hyemalis": "Pato havelda",
  "Coccothraustes coccothraustes": "Picogordo común",
  "Cochoa purpurea": "Cochoa púrpura",
  "Cochoa viridis": "Cochoa verde",
  "Coloeus dauuricus": "Grajilla oriental",
  "Coloeus monedula": "Grajilla occidental",
  "Columba eversmanni": "Paloma del Turquestán",
  "Columba hodgsonii": "Paloma de Hodgson",
  "Columba janthina": "Paloma japonesa",
  "Columba leuconota": "Paloma nival",
  "Columba livia": "Paloma bravía",
  "Columba oenas": "Paloma zurita",
  "Columba palumbus": "Paloma torcaz",
  "Columba pulchricollis": "Paloma cenicienta",
  "Columba punicea": "Paloma purpúrea",
  "Columba rupestris": "Paloma rupestre",
  "Columba vitiensis": "Paloma gorjiblanca",
  "Copsychus malabaricus": "Shama malabar",
  "Copsychus saularis": "Shama oriental",
  "Coracias affinis": "Carraca indochina",
  "Coracias garrulus": "Carraca europea",
  "Coracina javensis": "Oruguero de Java",
  "Corvus corax": "Cuervo grande",
  "Corvus cornix": "Corneja Cenicienta",
  "Corvus corone": "Corneja negra",
  "Corvus frugilegus": "Graja",
  "Corvus macrorhynchos": "Cuervo picudo",
  "Corvus splendens": "Cuervo indio",
  "Corvus torquatus": "Cuervo acollarado",
  "Coturnicops exquisitus": "Polluela exquisita",
  "Coturnix coromandelica": "Codorniz coromandélica",
  "Coturnix coturnix": "Codorniz común",
  "Coturnix japonica": "Codorniz japonesa",
  "Crex crex": "Guión de codornices",
  "Crossoptilon auritum": "Faisán orejudo azul",
  "Crossoptilon crossoptilon": "Faisán orejudo blanco",
  "Crossoptilon harmani": "Faisán orejudo gris",
  "Crossoptilon mantchuricum": "Faisán orejudo pardo",
  "Cuculus canorus": "Cuco común",
  "Cuculus micropterus": "Cuco alicorto",
  "Cuculus optatus": "Cuco de Horsfield",
  "Cuculus poliocephalus": "Cuco chico",
  "Cuculus saturatus": "Cuco oriental",
  "Culicicapa ceylonensis": "Papamoscas cabecigrís",
  "Curruca communis": "Curruca zarcera",
  "Curruca crassirostris": "Curruca mirlona oriental",
  "Curruca curruca": "Curruca zarcerilla",
  "Curruca nana": "Curruca enana",
  "Curruca nisoria": "Curruca gavilana",
  "Cutia nipalensis": "Cutia nepalesa",
  "Cyanistes cyanus": "Herrerillo azul",
  "Cyanoderma chrysaeum": "Timalí dorado",
  "Cyanoderma pyrrhops": "Timalí barbinegro",
  "Cyanoderma ruficeps": "Timalí coronirrojo",
  "Cyanoderma rufifrons": "Timalí frentirrufo",
  "Cyanopica cyanus": "Rabilargo asiático",
  "Cyanoptila cumatilis": "Papamoscas de Zappey",
  "Cyanoptila cyanomelana": "Papamoscas azul",
  "Cygnus columbianus": "Cisne chico",
  "Cygnus cygnus": "Cisne cantor",
  "Cygnus olor": "Cisne vulgar",
  "Cyornis brunneatus": "Papamoscas pechipardo",
  "Cyornis glaucicomans": "Papamoscas chino",
  "Cyornis hainanus": "Papamoscas de Hainan",
  "Cyornis magnirostris": "Papamoscas de Arunachal Pradesh",
  "Cyornis poliogenys": "Papamoscas de Brooks",
  "Cyornis rubeculoides": "Papamoscas gorjiazul",
  "Cyornis unicolor": "Papamoscas azulado",
  "Cyornis whitei": "Papamoscas pechiclaro",
  "Cypsiurus balasiensis": "Vencejo palmero asiático",
  "Delichon dasypus": "Avión asiático",
  "Delichon lagopodum": "Avión común oriental",
  "Delichon nipalense": "Avión nepalí",
  "Delichon urbicum": "Avión común occidental",
  "Dendrocitta formosae": "Urraca gris",
  "Dendrocitta frontalis": "Urraca acollarada",
  "Dendrocitta vagabunda": "Urraca vagabunda",
  "Dendrocopos atratus": "Pico estriado",
  "Dendrocopos darjellensis": "Pico de Darjeeling",
  "Dendrocopos hyperythrus": "Pico ventrirrufo",
  "Dendrocopos leucopterus": "Pico aliblanco",
  "Dendrocopos leucotos": "Pico dorsiblanco",
  "Dendrocopos macei": "Pico pechileonado",
  "Dendrocopos major": "Pico picapinos",
  "Dendrocoptes auriceps": "Pico frentipardo",
  "Dendrocygna javanica": "Suirirí de Java",
  "Dendronanthus indicus": "Lavandera forestal",
  "Dicaeum cruentatum": "Picaflores dorsirrojo",
  "Dicaeum ignipectus": "Picaflores pechofuego",
  "Dicaeum minullum": "Picaflores sencillo",
  "Dicrurus aeneus": "Drongo bronceado",
  "Dicrurus annectens": "Drongo picogordo",
  "Dicrurus hottentottus": "Drongo crestudo",
  "Dicrurus leucophaeus": "Drongo cenizo",
  "Dicrurus macrocercus": "Drongo real",
  "Dicrurus paradiseus": "Drongo de raquetas grande",
  "Dicrurus remifer": "Drongo de raquetas chico",
  "Dinopium javanense": "Pito culirrojo de Java",
  "Dryobates cathpharius": "Pico pechirrojo occidental",
  "Dryobates minor": "Pico menor",
  "Dryobates pernyii": "Pico pechirrojo oriental",
  "Dryocopus javensis": "Picamaderos ventriblanco",
  "Dryocopus martius": "Picamaderos negro",
  "Ducula aenea": "Dúcula verde",
  "Ducula badia": "Dúcula dorsicastaña",
  "Egretta eulophotes": "Garceta china",
  "Egretta garzetta": "Garceta común",
  "Egretta novaehollandiae": "Garceta cariblanca",
  "Egretta picata": "Garceta pía",
  "Egretta sacra": "Garceta de arrecife",
  "Elachura formosa": "Ratina moteada",
  "Elanus caeruleus": "Elanio común",
  "Emberiza aureola": "Escribano aureolado",
  "Emberiza bruniceps": "Escribano carirrojo",
  "Emberiza buchanani": "Escribano cabecigrís",
  "Emberiza calandra": "Escribano triguero",
  "Emberiza chrysophrys": "Escribano cejigualdo",
  "Emberiza cia": "Escribano montesino",
  "Emberiza cioides": "Escribano de Brandt",
  "Emberiza citrinella": "Escribano cerillo",
  "Emberiza elegans": "Escribano elegante",
  "Emberiza fucata": "Escribano orejudo",
  "Emberiza godlewskii": "Escribano de Godlewski",
  "Emberiza hortulana": "Escribano hortelano",
  "Emberiza jankowskii": "Escribano de Jankowski",
  "Emberiza koslowi": "Escribano tibetano",
  "Emberiza lathami": "Escribano crestado",
  "Emberiza leucocephalos": "Escribano cabeciblanco",
  "Emberiza melanocephala": "Escribano cabecinegro",
  "Emberiza pallasi": "Escribano de Pallas",
  "Emberiza personata": "Escribano enmascarado",
  "Emberiza pusilla": "Escribano pigmeo",
  "Emberiza rustica": "Escribano rústico",
  "Emberiza rutila": "Escribano herrumbroso",
  "Emberiza schoeniclus": "Escribano palustre",
  "Emberiza siemsseni": "Escribano azul",
  "Emberiza spodocephala": "Escribano carinegro",
  "Emberiza stewarti": "Escribano de Stewart",
  "Emberiza sulphurata": "Escribano japonés",
  "Emberiza tristrami": "Escribano de Tristram",
  "Emberiza variabilis": "Escribano gris",
  "Emberiza yessoensis": "Escribano culiocre",
  "Enicurus immaculatus": "Torrentero dorsinegro",
  "Enicurus leschenaulti": "Torrentero coroniblanco",
  "Enicurus maculatus": "Torrentero moteado",
  "Enicurus schistaceus": "Torrentero dorsigrís",
  "Enicurus scouleri": "Torrentero chico",
  "Eophona migratoria": "Picogordo chino",
  "Eophona personata": "Picogordo japonés",
  "Eremophila alpestris": "Alondra cornuda",
  "Erithacus rubecula": "Petirrojo europeo",
  "Erpornis zantholeuca": "Yuhina ventriblanca",
  "Erythrogenys erythrocnemis": "Cimitarra estriada",
  "Erythrogenys erythrogenys": "Cimitarra carirrufa",
  "Erythrogenys gravivox": "Cimitarra rayada",
  "Erythrogenys hypoleucos": "Cimitarra grande",
  "Erythrogenys swinhoei": "Cimitarra flanquigrís",
  "Erythrura prasina": "Diamante colifino",
  "Esacus recurvirostris": "Alcaraván piquigrueso indio",
  "Eudromias morinellus": "Chorlito carambolo",
  "Eudynamys scolopaceus": "Koel occidental",
  "Eumyias thalassinus": "Papamoscas verdín",
  "Eurystomus orientalis": "Carraca oriental",
  "Falcipennis falcipennis": "Gallo siberiano",
  "Falco amurensis": "Cernícalo del Amur",
  "Falco cherrug": "Halcón sacre",
  "Falco columbarius": "Esmerejón",
  "Falco naumanni": "Cernícalo primilla",
  "Falco peregrinus": "Halcón peregrino",
  "Falco rusticolus": "Halcón gerifalte",
  "Falco severus": "Alcotán filipino",
  "Falco subbuteo": "Alcotán europeo",
  "Falco tinnunculus": "Cernícalo vulgar",
  "Falco vespertinus": "Cernícalo patirrojo",
  "Ficedula albicilla": "Papamoscas de la taiga",
  "Ficedula elisae": "Papamoscas de Elise",
  "Ficedula erithacus": "Papamoscas pechirrojo",
  "Ficedula hodgsoni": "Papamoscas pigmeo",
  "Ficedula hyperythra": "Papamoscas cejiníveo",
  "Ficedula hypoleuca": "Papamoscas cerrojillo",
  "Ficedula mugimaki": "Papamoscas mugimaki",
  "Ficedula narcissina": "Papamoscas narciso",
  "Ficedula owstoni": "Papamoscas de las Ryukyu",
  "Ficedula parva": "Papamoscas papirrojo",
  "Ficedula ruficauda": "Papamoscas colirrojo",
  "Ficedula sapphira": "Papamoscas zafiro",
  "Ficedula strophiata": "Papamoscas gorjirrojo",
  "Ficedula superciliaris": "Papamoscas ultramarino",
  "Ficedula tricolor": "Papamoscas tricolor",
  "Ficedula westermanni": "Papamoscas pío",
  "Ficedula zanthopygia": "Papamoscas culiamarillo",
  "Francolinus pintadeanus": "Francolín chino",
  "Fregata andrewsi": "Rabihorcado de la Christmas",
  "Fregata ariel": "Rabihorcado chico",
  "Fregata minor": "Rabihorcado grande",
  "Fringilla coelebs": "Pinzón vulgar",
  "Fringilla montifringilla": "Pinzón real",
  "Fulica atra": "Focha común",
  "Fulmarus glacialis": "Fulmar boreal",
  "Fulvetta cinereiceps": "Fulveta encapuchada",
  "Fulvetta danisi": "Fulveta indochina",
  "Fulvetta formosana": "Fulveta de Formosa",
  "Fulvetta ludlowi": "Fulveta de Ludlow",
  "Fulvetta manipurensis": "Fulveta de Manipur",
  "Fulvetta ruficapilla": "Fulveta de Verreaux",
  "Fulvetta striaticollis": "Fulveta china",
  "Fulvetta vinipectus": "Fulveta cejiblanca",
  "Galerida cristata": "Cogujada común",
  "Gallicrex cinerea": "Gallineta crestada",
  "Gallinago gallinago": "Agachadiza común",
  "Gallinago hardwickii": "Agachadiza japonesa",
  "Gallinago megala": "Agachadiza del Baikal",
  "Gallinago nemoricola": "Agachadiza del Himalaya",
  "Gallinago solitaria": "Agachadiza solitaria",
  "Gallinago stenura": "Agachadiza colirrara",
  "Gallinula chloropus": "Gallineta común",
  "Gallus gallus": "Gallo bankiva",
  "Gampsorhynchus rufulus": "Timalí cabeciblanco",
  "Gampsorhynchus torquatus": "Timalí acollarado",
  "Garrulax canorus": "Charlatán canoro",
  "Garrulax castanotis": "Charlatán carirrufo",
  "Garrulax leucolophus": "Charlatán crestiblanco",
  "Garrulax maesi": "Charlatán de Maës",
  "Garrulax merulinus": "Charlatán pechipinto",
  "Garrulax monileger": "Charlatán acollarado chico",
  "Garrulax strepitans": "Charlatán cuelliblanco",
  "Garrulax taewanus": "Charlatán de Formosa",
  "Garrulus glandarius": "Arrendajo euroasiático",
  "Gavia adamsii": "Colimbo de Adams",
  "Gavia arctica": "Colimbo ártico",
  "Gavia pacifica": "Colimbo del Pacífico",
  "Gavia stellata": "Colimbo chico",
  "Gecinulus grantia": "Pito del bambú norteño",
  "Gelochelidon nilotica": "Pagaza piconegra",
  "Geokichla citrina": "Zorzal citrino",
  "Geokichla sibirica": "Zorzal siberiano",
  "Geokichla wardii": "Zorzal de Ward",
  "Geopelia striata": "Tortolita estriada",
  "Glareola lactea": "Canastera chica",
  "Glareola maldivarum": "Canastera oriental",
  "Glareola nordmanni": "Canastera alinegra",
  "Glareola pratincola": "Canastera común",
  "Glaucidium cuculoides": "Mochuelo cuco",
  "Glaucidium passerinum": "Mochuelo alpino",
  "Gorsachius goisagi": "Martinete japonés",
  "Gorsachius melanolophus": "Martinete malayo",
  "Gracula religiosa": "Miná religioso",
  "Gracupica contra": "Estornino pío común",
  "Gracupica nigricollis": "Estornino cuellinegro",
  "Graminicola striatus": "Yerbera china",
  "Grammatoptila striata": "Charlatán estriado",
  "Grandala coelicolor": "Zorzal grandala",
  "Grus grus": "Grulla común",
  "Grus japonensis": "Grulla manchú",
  "Grus monacha": "Grulla monje",
  "Grus nigricollis": "Grulla cuellinegra",
  "Grus virgo": "Grulla damisela",
  "Gygis alba": "Charrán blanco común",
  "Gypaetus barbatus": "Quebrantahuesos",
  "Gyps bengalensis": "Buitre dorsiblanco bengalí",
  "Gyps fulvus": "Buitre leonado",
  "Gyps himalayensis": "Buitre del Himalaya",
  "Gyps tenuirostris": "Buitre picofino",
  "Gypsophila annamensis": "Ratina de Annam",
  "Gypsophila brevicaudata": "Ratina colicorta",
  "Haematopus ostralegus": "Ostrero euroasiático",
  "Halcyon coromanda": "Alción rojizo",
  "Halcyon pileata": "Alción capirotado",
  "Halcyon smyrnensis": "Alción de Esmirna",
  "Haliaeetus albicilla": "Pigargo europeo",
  "Haliaeetus leucoryphus": "Pigargo de Pallas",
  "Haliaeetus pelagicus": "Pigargo gigante",
  "Haliastur indus": "Milano brahmán",
  "Harpactes erythrocephalus": "Trogón cabecirrojo",
  "Harpactes oreskios": "Trogón pechinaranja",
  "Harpactes wardi": "Trogón de Ward",
  "Helopsaltes amnicola": "Buscarla de Sajalín",
  "Helopsaltes certhiola": "Buscarla de Pallas",
  "Helopsaltes fasciolatus": "Buscarla de Gray",
  "Helopsaltes ochotensis": "Buscarla de Middendorff",
  "Helopsaltes pleskei": "Buscarla de Pleske",
  "Helopsaltes pryeri": "Yerbera japonesa",
  "Hemiprocne coronata": "Vencejo arborícola coronado",
  "Hemipus picatus": "Oruguero alibarrado",
  "Hemitesia pallidipes": "Tesia paticlara",
  "Hemixos castanonotus": "Bulbul castaño",
  "Hemixos flavala": "Bulbul ceniciento",
  "Heterophasia auricularis": "Sibia orejiblanca",
  "Heterophasia capistrata": "Sibia rufa",
  "Heterophasia desgodinsi": "Sibia cabecinegra",
  "Heterophasia gracilis": "Sibia gris",
  "Heterophasia picaoides": "Sibia colilarga",
  "Heterophasia pulchella": "Sibia bonita",
  "Heteroxenicus stellatus": "Alicorto estrellado",
  "Hieraaetus pennatus": "Águila calzada",
  "Hierococcyx hyperythrus": "Cuco ventrirrojo",
  "Hierococcyx nisicolor": "Cuco silbador",
  "Hierococcyx sparverioides": "Cuco grande",
  "Hierococcyx varius": "Cuco chikra",
  "Himantopus himantopus": "Cigüeñuela común",
  "Himantopus leucocephalus": "Cigüeñuela Pechirroja",
  "Hirundapus caudacutus": "Vencejo mongol",
  "Hirundapus celebensis": "Vencejo de Célebes",
  "Hirundapus cochinchinensis": "Vencejo de la Cochinchina",
  "Hirundapus giganteus": "Vencejo gigante",
  "Hirundo javanica": "Golondrina del Pacífico",
  "Hirundo rustica": "Golondrina común",
  "Hirundo smithii": "Golondrina colilarga",
  "Histrionicus histrionicus": "Pato arlequín",
  "Horornis acanthizoides": "Cetia ventrigulada",
  "Horornis brunnescens": "Cetia del Himalaya",
  "Horornis canturians": "Cetia coreana",
  "Horornis diphone": "Cetia japonesa",
  "Horornis flavolivaceus": "Cetia verdiamarilla",
  "Horornis fortipes": "Cetia montana",
  "Hydrobates leucorhous": "Paíño boreal",
  "Hydrobates matsudairae": "Paíño de Matsudaira",
  "Hydrobates monorhis": "Paíño de Swinhoe",
  "Hydrobates tristrami": "Paíño de Tristram",
  "Hydrocoloeus minutus": "Gaviota enana",
  "Hydrophasianus chirurgus": "Jacana colilarga",
  "Hydroprogne caspia": "Pagaza piquirroja",
  "Hydrornis cyaneus": "Pita azul",
  "Hydrornis nipalensis": "Pita nuquiazul",
  "Hydrornis oatesi": "Pita rojiza",
  "Hydrornis phayrei": "Pita orejuda",
  "Hydrornis soror": "Pita lomiazul",
  "Hypothymis azurea": "Monarca nuquinegro",
  "Hypsipetes amaurotis": "Bulbul orejipardo",
  "Hypsipetes leucocephalus": "Bulbul negro",
  "Ianthocincla bieti": "Charlatán de Biet",
  "Ianthocincla cineracea": "Charlatán ceniciento occidental",
  "Ianthocincla lunulata": "Charlatán lunado",
  "Ianthocincla maxima": "Charlatán gigante",
  "Ianthocincla ocellata": "Charlatán ocelado",
  "Ianthocincla rufogularis": "Charlatán golirrufo",
  "Ianthocincla sukatschewi": "Charlatán de Sukatschev",
  "Ibidorhyncha struthersii": "Picoibis",
  "Ichthyaetus ichthyaetus": "Gavión cabecinegro",
  "Ichthyaetus relictus": "Gaviota relicta",
  "Icthyophaga humilis": "Pigarguillo menor",
  "Icthyophaga leucogaster": "Pigargo oriental",
  "Ictinaetus malaiensis": "Águila milana",
  "Iduna caligata": "Zarcero escita",
  "Iduna pallida": "Zarcero pálido",
  "Iduna rama": "Zarcero de Sykes",
  "Indicator xanthonotus": "Indicador indio",
  "Iole propinqua": "Bulbul ojigrís",
  "Irena puella": "Irena común",
  "Ithaginis cruentus": "Faisán ensangrentado",
  "Ixos mcclellandii": "Bulbul de McClelland",
  "Jynx torquilla": "Torcecuello euroasiático",
  "Ketupa blakistoni": "Búho manchú",
  "Ketupa coromanda": "Búho de Coromandel",
  "Ketupa flavipes": "Búho pescador leonado",
  "Ketupa nipalensis": "Búho nepalí",
  "Ketupa zeylonensis": "Búho pescador de Ceilán",
  "Kurochkinegramma hypogrammicum": "Arañero nuquiazul",
  "Lagopus lagopus": "Lagópodo común",
  "Lagopus muta": "Lagópodo alpino",
  "Lalage melaschistos": "Oruguero alinegro",
  "Lalage nigra": "Oruguero pío",
  "Lanius borealis": "Alcaudón boreal",
  "Lanius bucephalus": "Alcaudón bucéfalo",
  "Lanius collurio": "Alcaudón dorsirrojo",
  "Lanius collurioides": "Alcaudón birmano",
  "Lanius cristatus": "Alcaudón pardo",
  "Lanius excubitor": "Alcaudón norteño",
  "Lanius isabellinus": "Alcaudón isabel",
  "Lanius minor": "Alcaudón chico",
  "Lanius phoenicuroides": "Alcaudón colirrojo",
  "Lanius schach": "Alcaudón schach",
  "Lanius sphenocercus": "Alcaudón chino",
  "Lanius tephronotus": "Alcaudón tibetano",
  "Lanius tigrinus": "Alcaudón tigre",
  "Lanius vittatus": "Alcaudón dorsicastaño",
  "Larus brachyrhynchus": "Gaviota piquicorta",
  "Larus cachinnans": "Gaviota del Caspio",
  "Larus canus": "Gaviota cana",
  "Larus crassirostris": "Gaviota japonesa",
  "Larus delawarensis": "Gaviota de Delaware",
  "Larus fuscus": "Gaviota sombría",
  "Larus glaucescens": "Gaviota de Bering",
  "Larus hyperboreus": "Gavión hiperbóreo",
  "Larus schistisagus": "Gaviota de Kamchatka",
  "Larus vegae": "Gaviota del este de Siberia",
  "Larvivora akahige": "Ruiseñor japonés",
  "Larvivora brunnea": "Ruiseñor indio",
  "Larvivora cyane": "Ruiseñor azul",
  "Larvivora komadori": "Ruiseñor de las Ryukyu",
  "Larvivora ruficeps": "Ruiseñor cabecirrojo",
  "Larvivora sibilans": "Ruiseñor silbador",
  "Leioptila annectens": "Sibia dorsirrufa",
  "Leiothrix argentauris": "Leiótrix cariblanco",
  "Leiothrix lutea": "Leiótrix piquirrojo",
  "Leptopoecile elegans": "Carbonerito elegante",
  "Leptopoecile sophiae": "Carbonerito de Sophie",
  "Leptoptilos javanicus": "Marabú menor",
  "Lerwa lerwa": "Perdiz lerwa",
  "Leucogeranus leucogeranus": "Grulla siberiana",
  "Leucophaeus atricilla": "Gaviota guanaguanare",
  "Leucophaeus pipixcan": "Gaviota pipizcan",
  "Leucoptilon concretum": "Papamoscas coliblanco",
  "Leucosticte arctoa": "Pinzón montano pardo",
  "Leucosticte brandti": "Pinzón montano de Brandt",
  "Leucosticte nemoricola": "Pinzón montano de Hodgson",
  "Lewinia striata": "Rascón rufigrís",
  "Limnodromus scolopaceus": "Agujeta escolopácea",
  "Limnodromus semipalmatus": "Agujeta asiática",
  "Limosa lapponica": "Aguja colipinta",
  "Limosa limosa": "Aguja colinegra",
  "Linaria cannabina": "Pardillo común",
  "Linaria flavirostris": "Pardillo piquigualdo",
  "Liocichla omeiensis": "Charlatán del Omei",
  "Liocichla phoenicea": "Charlatán carirrojo",
  "Liocichla ripponi": "Charlatán de Rippon",
  "Liocichla steerii": "Charlatán de Steere",
  "Lioparus chrysotis": "Fulveta dorada",
  "Locustella alishanensis": "Zarzalero de Formosa",
  "Locustella chengi": "Zarzalero de Sichuan",
  "Locustella davidi": "Zarzalero de David",
  "Locustella lanceolata": "Buscarla lanceolada",
  "Locustella luscinioides": "Buscarla unicolor",
  "Locustella luteoventris": "Zarzalero pardo",
  "Locustella major": "Zarzalero piquilargo",
  "Locustella mandelli": "Zarzalero de Mandelli",
  "Locustella naevia": "Buscarla pintoja",
  "Locustella tacsanowskia": "Zarzalero de Taczanowski",
  "Locustella thoracica": "Zarzalero moteado",
  "Lonchura atricapilla": "Capuchino castaño",
  "Lonchura punctulata": "Capuchino punteado",
  "Lonchura striata": "Capuchino culiblanco",
  "Lophophanes dichrous": "Herrerillo crestigrís",
  "Lophophorus impejanus": "Monal colirrojo",
  "Lophophorus lhuysii": "Monal coliverde",
  "Lophophorus sclateri": "Monal coliblanco",
  "Lophospiza trivirgata": "Azor moñudo",
  "Lophura leucomelanos": "Faisán kálij",
  "Lophura nycthemera": "Faisán plateado",
  "Lophura swinhoii": "Faisán de Swinhoe",
  "Loriculus vernalis": "Lorículo vernal",
  "Loxia curvirostra": "Piquituerto común",
  "Loxia leucoptera": "Piquituerto aliblanco",
  "Luscinia megarhynchos": "Ruiseñor común",
  "Luscinia phaenicuroides": "Colirrojo ventriblanco",
  "Luscinia svecica": "Ruiseñor pechiazul",
  "Lymnocryptes minimus": "Agachadiza chica",
  "Lyncornis macrotis": "Chotacabras orejudo",
  "Lyrurus tetrix": "Gallo lira común",
  "Machlolophus holsti": "Carbonero de Formosa",
  "Machlolophus spilonotus": "Carbonero carigualdo chino",
  "Machlolophus xanthogenys": "Carbonero carigualdo indio",
  "Macropygia ruficeps": "Tórtola cuco chica",
  "Macropygia tenuirostris": "Tórtola cuco filipina",
  "Macropygia unchall": "Tórtola cuco unchal",
  "Mareca americana": "Silbón americano",
  "Mareca falcata": "Cerceta de Alfanjes",
  "Mareca penelope": "Silbón europeo",
  "Mareca strepera": "Ánade friso",
  "Marmaronetta angustirostris": "Cerceta pardilla",
  "Megaceryle lugubris": "Martín gigante asiático",
  "Megalurus palustris": "Yerbera palustre",
  "Melanitta americana": "Negrón americano",
  "Melanitta fusca": "Negrón especulado",
  "Melanitta stejnegeri": "Negrón siberiano",
  "Melanochlora sultanea": "Carbonero sultán",
  "Melanocorypha bimaculata": "Calandria bimaculada",
  "Melanocorypha calandra": "Calandria común",
  "Melanocorypha maxima": "Calandria tibetana",
  "Melanocorypha mongolica": "Calandria de Mongolia",
  "Melanocorypha yeltoniensis": "Calandria negra",
  "Mergellus albellus": "Serreta chica",
  "Mergus merganser": "Serreta grande",
  "Mergus serrator": "Serreta mediana",
  "Mergus squamatus": "Serreta china",
  "Merops apiaster": "Abejaruco europeo",
  "Merops leschenaulti": "Abejaruco cabecirrufo",
  "Merops orientalis": "Abejaruco esmeralda oriental",
  "Merops ornatus": "Abejaruco australiano",
  "Merops persicus": "Abejaruco persa",
  "Merops philippinus": "Abejaruco coliazul",
  "Merops viridis": "Abejaruco gorjiazul",
  "Metopidius indicus": "Jacana bronceada",
  "Microcarbo niger": "Cormorán de Java",
  "Microcarbo pygmaeus": "Cormorán pigmeo",
  "Microhierax caerulescens": "Falconete acollarado",
  "Microhierax melanoleucos": "Falconete pío",
  "Micropternus brachyurus": "Carpintero rufo",
  "Milvus migrans": "Milano negro",
  "Minla ignotincta": "Minla colirroja",
  "Mirafra javanica": "Alondra de Java",
  "Mixornis gularis": "Timalí goliestriado",
  "Monticola cinclorhyncha": "Roquero capiazul",
  "Monticola gularis": "Roquero gorjiblanco",
  "Monticola rufiventris": "Roquero ventrirrufo",
  "Monticola saxatilis": "Roquero rojo",
  "Monticola solitarius": "Roquero solitario",
  "Montifringilla adamsi": "Gorrión de Adams",
  "Montifringilla henrici": "Gorrión de Henri",
  "Montifringilla nivalis": "Gorrión alpino",
  "Motacilla alba": "Lavandera blanca",
  "Motacilla cinerea": "Lavandera cascadeña",
  "Motacilla citreola": "Lavandera cetrina",
  "Motacilla flava": "Lavandera boyera",
  "Motacilla grandis": "Lavandera japonesa",
  "Motacilla maderaspatensis": "Lavandera india",
  "Motacilla tschutschensis": "Lavandera de Chukotka",
  "Moupinia poecilotis": "Timalí colirrufo",
  "Mulleripicus pulverulentus": "Picatroncos pizarroso",
  "Muscicapa dauurica": "Papamoscas asiático",
  "Muscicapa ferruginea": "Papamoscas herrumbroso",
  "Muscicapa griseisticta": "Papamoscas estriado",
  "Muscicapa muttui": "Papamoscas muttui",
  "Muscicapa sibirica": "Papamoscas siberiano",
  "Muscicapa striata": "Papamoscas gris",
  "Mycerobas affinis": "Picogordo acollarado",
  "Mycerobas carnipes": "Picogordo aliblanco",
  "Mycerobas melanozanthos": "Picogordo alimoteado",
  "Mycteria leucocephala": "Tántalo indio",
  "Myiomela leucura": "Ruiseñor coliblanco",
  "Myophonus caeruleus": "Arrenga común",
  "Myophonus insularis": "Arrenga de Formosa",
  "Myzornis pyrrhoura": "Timalí melero",
  "Napothera epilepidota": "Ratina cejuda",
  "Napothera malacoptila": "Ratina picuda",
  "Napothera naungmungensis": "Ratina de Naung Mung",
  "Neophron percnopterus": "Alimoche común",
  "Netta rufina": "Pato colorado",
  "Nettapus coromandelianus": "Gansito asiático",
  "Niltava davidi": "Papamoscas de David",
  "Niltava grandis": "Papamoscas grande",
  "Niltava macgrigoriae": "Papamoscas de McGrigor",
  "Niltava oatesi": "Papamoscas vívido grande",
  "Niltava sundara": "Papamoscas sundara",
  "Niltava vivida": "Papamoscas vívido chico",
  "Ninox japonica": "Nínox japonés",
  "Ninox scutulata": "Nínox pardo",
  "Nipponia nippon": "Ibis nipón",
  "Nisaetus cirrhatus": "Águila variable",
  "Nisaetus nipalensis": "Águila montañesa",
  "Nucifraga caryocatactes": "Cascanueces norteño",
  "Nucifraga hemispila": "Cascanueces sureño",
  "Nucifraga multipunctata": "Cascanueces del Himalaya",
  "Numenius arquata": "Zarapito real",
  "Numenius madagascariensis": "Zarapito siberiano",
  "Numenius minutus": "Zarapito chico",
  "Numenius phaeopus": "Zarapito trinador",
  "Nycticorax caledonicus": "Martinete canelo",
  "Nycticorax nycticorax": "Martinete común",
  "Nyctyornis athertoni": "Abejaruco barbiazul",
  "Oceanites oceanicus": "Paíño de Wilson",
  "Oenanthe deserti": "Collalba desértica",
  "Oenanthe isabellina": "Collalba isabel",
  "Oenanthe oenanthe": "Collalba gris",
  "Oenanthe picata": "Collalba variable",
  "Oenanthe pleschanka": "Collalba pía",
  "Onychoprion aleuticus": "Charrán aleutiano",
  "Onychoprion anaethetus": "Charrán embridado",
  "Onychoprion fuscatus": "Charrán sombrío",
  "Onychostruthus taczanowskii": "Gorrión de Taczanowski",
  "Oriolus chinensis": "Oropéndola china",
  "Oriolus kundoo": "Oropéndola india",
  "Oriolus mellianus": "Oropéndola plateada",
  "Oriolus oriolus": "Oropéndola europea",
  "Oriolus tenuirostris": "Oropéndola picofina",
  "Oriolus traillii": "Oropéndola granate",
  "Oriolus xanthornus": "Oropéndola encapuchada",
  "Oroanassa magnifica": "Martinete magnífico",
  "Orthotomus atrogularis": "Sastrecillo cuellinegro",
  "Orthotomus sutorius": "Sastrecillo común",
  "Otis tarda": "Avutarda euroasiática",
  "Otus brucei": "Autillo persa",
  "Otus elegans": "Autillo elegante",
  "Otus lettia": "Autillo chino",
  "Otus scops": "Autillo europeo",
  "Otus semitorques": "Autillo japonés",
  "Otus spilocephalus": "Autillo montano",
  "Otus sunia": "Autillo oriental",
  "Oxyura leucocephala": "Malvasía cabeciblanca",
  "Pandion haliaetus": "Águila pescadora",
  "Panurus biarmicus": "Bigotudo",
  "Paradoxornis aemodius": "Picoloro grande",
  "Paradoxornis bakeri": "Picoloro cabecirrufo oriental",
  "Paradoxornis gularis": "Picoloro cabecigrís",
  "Paradoxornis guttaticollis": "Picoloro pechipinto",
  "Paradoxornis heudei": "Picoloro del Yangtsé",
  "Paradoxornis paradoxus": "Picoloro tridáctilo",
  "Paradoxornis ruficeps": "Picoloro cabecirrufo occidental",
  "Paradoxornis unicolor": "Picoloro unicolor",
  "Parayuhina diademata": "Yuhina diademada",
  "Parus cinereus": "Carbonero indio",
  "Parus major": "Carbonero común",
  "Parus monticolus": "Carbonero dorsiverde",
  "Passer ammodendri": "Gorrión del saxaul",
  "Passer cinnamomeus": "Gorrión rutilante",
  "Passer domesticus": "Gorrión común",
  "Passer hispaniolensis": "Gorrión moruno",
  "Passer montanus": "Gorrión molinero",
  "Passerculus sandwichensis": "Chingolo sabanero",
  "Pastor roseus": "Estornino rosado",
  "Pavo muticus": "Pavo real cuelliverde",
  "Pelargopsis capensis": "Alción picocigüeña",
  "Pelecanus crispus": "Pelícano ceñudo",
  "Pelecanus onocrotalus": "Pelícano común",
  "Pelecanus philippensis": "Pelícano oriental",
  "Pellorneum albiventre": "Tordina golipinta",
  "Pellorneum ruficeps": "Tordina pechiestriada",
  "Pellorneum tickelli": "Tordina de Tickell",
  "Perdix dauurica": "Perdiz dáurica",
  "Perdix hodgsoniae": "Perdiz tibetana",
  "Perdix perdix": "Perdiz pardilla",
  "Pericrocotus brevirostris": "Minivet piquicorto",
  "Pericrocotus cantonensis": "Minivet de Swinhoe",
  "Pericrocotus divaricatus": "Minivet ceniciento",
  "Pericrocotus ethologus": "Minivet colilargo",
  "Pericrocotus roseus": "Minivet rosado",
  "Pericrocotus solaris": "Minivet gorjigrís",
  "Pericrocotus speciosus": "Minivet escarlata",
  "Pericrocotus tegimae": "Minivet de las Ryukyu",
  "Periparus ater": "Carbonero garrapinos",
  "Periparus rubidiventris": "Carbonero culirrufo",
  "Periparus rufonuchalis": "Carbonero nuquirrufo",
  "Perisoreus infaustus": "Arrendajo siberiano",
  "Perisoreus internigrans": "Arrendajo de Sichuan",
  "Pernis apivorus": "Abejero europeo",
  "Pernis ptilorhynchus": "Abejero oriental",
  "Petrochelidon fluvicola": "Golondrina india",
  "Petronia petronia": "Gorrión chillón",
  "Phaenicophaeus tristis": "Malcoha sombrío",
  "Phaethon aethereus": "Rabijunco etéreo",
  "Phaethon lepturus": "Rabijunco menor",
  "Phaethon rubricauda": "Rabijunco colirrojo",
  "Phalacrocorax capillatus": "Cormorán japonés",
  "Phalacrocorax carbo": "Cormorán grande",
  "Phalaropus fulicarius": "Falaropo picogrueso",
  "Phalaropus lobatus": "Falaropo picofino",
  "Phasianus colchicus": "Faisán vulgar",
  "Phodilus badius": "Lechuza cornuda oriental",
  "Phoebastria albatrus": "Albatros colicorto",
  "Phoebastria immutabilis": "Albatros de Laysan",
  "Phoebastria nigripes": "Albatros patinegro",
  "Phoenicopterus roseus": "Flamenco común",
  "Phoenicurus alaschanicus": "Colirrojo de Przewalski",
  "Phoenicurus auroreus": "Colirrojo dáurico",
  "Phoenicurus coeruleocephala": "Colirrojo capiazul",
  "Phoenicurus erythrogastrus": "Colirrojo de Güldenstädt",
  "Phoenicurus erythronotus": "Colirrojo de Eversmann",
  "Phoenicurus frontalis": "Colirrojo frentiazul",
  "Phoenicurus fuliginosus": "Colirrojo fuliginoso",
  "Phoenicurus hodgsoni": "Colirrojo de Hodgson",
  "Phoenicurus leucocephalus": "Colirrojo acuático",
  "Phoenicurus ochruros": "Colirrojo tizón",
  "Phoenicurus phoenicurus": "Colirrojo real",
  "Phoenicurus schisticeps": "Colirrojo gorjiblanco",
  "Phyllergates cucullatus": "Sastrecillo montano",
  "Phylloscopus affinis": "Mosquitero de Tickell",
  "Phylloscopus armandii": "Mosquitero de David",
  "Phylloscopus borealis": "Mosquitero boreal",
  "Phylloscopus borealoides": "Mosquitero borealoide",
  "Phylloscopus burkii": "Mosquitero de Burke",
  "Phylloscopus calciatilis": "Mosquitero roquero",
  "Phylloscopus cantator": "Mosquitero cantor",
  "Phylloscopus castaniceps": "Mosquitero coronicastaño",
  "Phylloscopus chloronotus": "Mosquitero dorsiclaro",
  "Phylloscopus claudiae": "Mosquitero de Claudia",
  "Phylloscopus collybita": "Mosquitero común",
  "Phylloscopus coronatus": "Mosquitero coronado",
  "Phylloscopus emeiensis": "Mosquitero del Emei",
  "Phylloscopus examinandus": "Mosquitero de Kamchatka",
  "Phylloscopus forresti": "Mosquitero de Sichuan",
  "Phylloscopus fuligiventer": "Mosquitero ahumado",
  "Phylloscopus fuscatus": "Mosquitero sombrío",
  "Phylloscopus goodsoni": "Mosquitero de Hartert",
  "Phylloscopus griseolus": "Mosquitero del Pamir",
  "Phylloscopus hainanus": "Mosquitero de Hainan",
  "Phylloscopus humei": "Mosquitero de Hume",
  "Phylloscopus ijimae": "Mosquitero de Ijima",
  "Phylloscopus inornatus": "Mosquitero bilistado",
  "Phylloscopus intensior": "Mosquitero de Davison",
  "Phylloscopus intermedius": "Mosquitero de anteojos",
  "Phylloscopus kansuensis": "Mosquitero de Gansu",
  "Phylloscopus maculipennis": "Mosquitero gorjigrís",
  "Phylloscopus magnirostris": "Mosquitero picudo",
  "Phylloscopus ogilviegranti": "Mosquitero de Ogilvie Grant",
  "Phylloscopus omeiensis": "Mosquitero de Martens",
  "Phylloscopus plumbeitarsus": "Mosquitero patigrís",
  "Phylloscopus poliogenys": "Mosquitero carigrís",
  "Phylloscopus proregulus": "Mosquitero de Pallas",
  "Phylloscopus pulcher": "Mosquitero elegante",
  "Phylloscopus reguloides": "Mosquitero de Blyth",
  "Phylloscopus ricketti": "Mosquitero de Rickett",
  "Phylloscopus schwarzi": "Mosquitero de Schwarz",
  "Phylloscopus sibilatrix": "Mosquitero silbador",
  "Phylloscopus sindianus": "Mosquitero montano",
  "Phylloscopus soror": "Mosquitero soror",
  "Phylloscopus subaffinis": "Mosquitero gorjiclaro",
  "Phylloscopus tenellipes": "Mosquitero paticlaro",
  "Phylloscopus tephrocephalus": "Mosquitero coronigrís",
  "Phylloscopus trochiloides": "Mosquitero verdoso",
  "Phylloscopus trochilus": "Mosquitero musical",
  "Phylloscopus valentini": "Mosquitero de Bianchi",
  "Phylloscopus whistleri": "Mosquitero de Whistler",
  "Phylloscopus xanthodryas": "Mosquitero japonés",
  "Phylloscopus xanthoschistos": "Mosquitero cabecigrís",
  "Phylloscopus yunnanensis": "Mosquitero de Yunnan",
  "Pica bottanensis": "Urraca del himalaya",
  "Pica pica": "Urraca común",
  "Pica serica": "Urraca oriental",
  "Picoides tridactylus": "Pico tridáctilo",
  "Picumnus innominatus": "Carpinterito moteado",
  "Picus canus": "Pito cano",
  "Picus chlorolophus": "Pito crestigualdo",
  "Picus rabieri": "Pito vietnamita",
  "Picus squamatus": "Pito escamoso",
  "Picus vittatus": "Pito colinegro",
  "Picus xanthopygaeus": "Pito culigualdo",
  "Pinicola enucleator": "Camachuelo picogrueso",
  "Pitta brachyura": "Pita india",
  "Pitta moluccensis": "Pita aliazul",
  "Pitta nympha": "Pita ninfa",
  "Pitta sordida": "Pita encapuchada occidental",
  "Platalea leucorodia": "Espátula común",
  "Platalea minor": "Espátula menor",
  "Plectrophenax nivalis": "Escribano nival",
  "Plegadis falcinellus": "Morito común",
  "Ploceus manyar": "Tejedor estriado",
  "Ploceus philippinus": "Tejedor baya",
  "Pluvialis apricaria": "Chorlito dorado europeo",
  "Pluvialis dominica": "Chorlito dorado americano",
  "Pluvialis fulva": "Chorlito dorado siberiano",
  "Pluvialis squatarola": "Chorlito gris",
  "Pnoepyga albiventer": "Ratina ventriblanca",
  "Pnoepyga formosana": "Ratina de Formosa",
  "Pnoepyga immaculata": "Ratina inmaculada",
  "Pnoepyga pusilla": "Ratina pigmea",
  "Podiceps auritus": "Zampullín cuellirrojo",
  "Podiceps cristatus": "Somormujo lavanco",
  "Podiceps grisegena": "Somormujo cuellirrojo",
  "Podiceps nigricollis": "Zampullín cuellinegro",
  "Podoces biddulphi": "Arrendajo terrestre de Xinjiang",
  "Podoces hendersoni": "Arrendajo terrestre mongol",
  "Poecile davidi": "Carbonero de David",
  "Poecile hypermelaenus": "Carbonero barbinegro",
  "Poecile montanus": "Carbonero montano",
  "Poecile palustris": "Carbonero palustre",
  "Poecile superciliosus": "Carbonero cejiblanco",
  "Poecile weigoldicus": "Carbonero de Sichuán",
  "Poliolimnas cinereus": "Polluela cejiblanca",
  "Polyplectron bicalcaratum": "Espolonero chinquis",
  "Polyplectron katsumatae": "Espolonero de Hainán",
  "Polysticta stelleri": "Éider menor",
  "Pomatorhinus ferruginosus": "Cimitarra coralina",
  "Pomatorhinus musicus": "Cimitarra de Formosa",
  "Pomatorhinus ochraceiceps": "Cimitarra piquirroja",
  "Pomatorhinus phayrei": "Cimitarra coroniparda",
  "Pomatorhinus ruficollis": "Cimitarra cuellirrufa",
  "Pomatorhinus schisticeps": "Cimitarra cejiblanca",
  "Pomatorhinus superciliaris": "Cimitarra picofina",
  "Porphyrio indicus": "Calamón dorsinegro",
  "Porphyrio poliocephalus": "Calamón cabecigrís",
  "Porzana porzana": "Polluela pintoja",
  "Prinia atrogularis": "Prinia gorjinegra",
  "Prinia crinigera": "Prinia del Himalaya",
  "Prinia flaviventris": "Prinia ventriamarilla",
  "Prinia hodgsonii": "Prinia de Hodgson",
  "Prinia inornata": "Prinia sencilla",
  "Prinia rufescens": "Prinia rojiza",
  "Prinia striata": "Prinia estriada",
  "Prinia superciliaris": "Prinia montana",
  "Procarduelis nipalensis": "Camachuelo oscuro",
  "Prunella atrogularis": "Acentor gorjinegro",
  "Prunella collaris": "Acentor alpino",
  "Prunella fulvescens": "Acentor pardo",
  "Prunella himalayana": "Acentor del Himalaya",
  "Prunella immaculata": "Acentor inmaculado",
  "Prunella koslowi": "Acentor mongol",
  "Prunella montanella": "Acentor siberiano",
  "Prunella rubeculoides": "Acentor petirrojo",
  "Prunella strophiata": "Acentor pechirrufo",
  "Psarisomus dalhousiae": "Eurilaimo lorito",
  "Pseudibis davisoni": "Ibis de Davison",
  "Pseudobulweria rostrata": "Petrel de Tahití",
  "Pseudopodoces humilis": "Carbonero terrestre",
  "Psilopogon asiaticus": "Barbudo gorjiazul común",
  "Psilopogon cyanotis": "Barbudo orejiazul",
  "Psilopogon faber": "Barbudo chino",
  "Psilopogon faiostrictus": "Barbudo orejiverde",
  "Psilopogon franklinii": "Barbudo de Franklin",
  "Psilopogon haemacephalus": "Barbudo calderero",
  "Psilopogon lineatus": "Barbudo listado",
  "Psilopogon nuchalis": "Barbudo de Formosa",
  "Psilopogon virens": "Barbudo grande",
  "Psittacula alexandri": "Cotorra pechirroja",
  "Psittacula derbiana": "Cotorra de Derby",
  "Psittacula eupatria": "Cotorra alejandrina",
  "Psittacula finschii": "Cotorra de Finsch",
  "Psittacula himalayana": "Cotorra del Himalaya",
  "Psittacula krameri": "Cotorra de Kramer",
  "Psittacula roseata": "Cotorra carirrosa",
  "Psittinus cyanurus": "Lorito dorsiazul",
  "Pterocles orientalis": "Ganga ortega",
  "Pterodroma heraldica": "Petrel del Herald",
  "Pterodroma hypoleuca": "Petrel de las Bonin",
  "Pterodroma solandri": "Petrel de Solander",
  "Pterorhinus albogularis": "Charlatán gorjiblanco",
  "Pterorhinus berthemyi": "Charlatán rojizo chino",
  "Pterorhinus caerulatus": "Charlatán flanquigrís",
  "Pterorhinus chinensis": "Charlatán golinegro",
  "Pterorhinus courtoisi": "Charlatán coroniazul",
  "Pterorhinus davidi": "Charlatán de David",
  "Pterorhinus galbanus": "Charlatán goligualdo",
  "Pterorhinus gularis": "Charlatán culirrufo",
  "Pterorhinus koslowi": "Babax de Koslov",
  "Pterorhinus lanceolatus": "Babax chino",
  "Pterorhinus pectoralis": "Charlatán acollarado grande",
  "Pterorhinus perspicillatus": "Charlatán enmascarado",
  "Pterorhinus poecilorhynchus": "Charlatán rojizo de Formosa",
  "Pterorhinus ruficeps": "Charlatán coronirrufo",
  "Pterorhinus ruficollis": "Charlatán cuellirrufo",
  "Pterorhinus sannio": "Charlatán payaso",
  "Pterorhinus waddelli": "Babax gigante",
  "Pteruthius aeralatus": "Vireo alcaudón cejiblanco",
  "Pteruthius intermedius": "Vireo alcaudón frenticastaño",
  "Pteruthius melanotis": "Vireo alcaudón orejudo",
  "Pteruthius rufiventer": "Vireo alcaudón ventrirrufo",
  "Pteruthius xanthochlorus": "Vireo alcaudón verde",
  "Ptyonoprogne concolor": "Avión oscuro",
  "Ptyonoprogne rupestris": "Avión roquero",
  "Pucrasia macrolopha": "Faisán koklas",
  "Puffinus nativitatis": "Pardela de Navidad",
  "Pycnonotus aurigaster": "Bulbul ventridorado",
  "Pycnonotus cafer": "Bulbul cafre",
  "Pycnonotus conradi": "Bulbul de Blanford oriental",
  "Pycnonotus finlaysoni": "Bulbul de Finlayson",
  "Pycnonotus flavescens": "Bulbul amarillento",
  "Pycnonotus goiavier": "Bulbul culiamarillo",
  "Pycnonotus jocosus": "Bulbul orfeo",
  "Pycnonotus leucogenys": "Bulbul cariblanco",
  "Pycnonotus sinensis": "Bulbul chino",
  "Pycnonotus taivanus": "Bulbul de Taiwan",
  "Pycnonotus xanthorrhous": "Bulbul pechipardo",
  "Pyrgilauda blanfordi": "Gorrión de Blanford",
  "Pyrgilauda davidiana": "Gorrión de David",
  "Pyrgilauda ruficollis": "Gorrión cuellirrufo",
  "Pyrrhocorax graculus": "Chova piquigualda",
  "Pyrrhocorax pyrrhocorax": "Chova piquirroja",
  "Pyrrhoplectes epauletta": "Pinzón nuquigualdo",
  "Pyrrhula erythaca": "Camachuelo cabecigrís",
  "Pyrrhula erythrocephala": "Camachuelo cabecirrojo",
  "Pyrrhula nipalensis": "Camachuelo pardo",
  "Pyrrhula owstoni": "Camachuelo de Taiwán",
  "Pyrrhula pyrrhula": "Camachuelo común",
  "Rallina eurizonoides": "Polluela de jungla",
  "Rallina fasciata": "Polluela patirroja",
  "Rallus aquaticus": "Rascón europeo",
  "Rallus indicus": "Rascón asiático",
  "Recurvirostra avosetta": "Avoceta común",
  "Regulus goodfellowi": "Reyezuelo de Formosa",
  "Regulus regulus": "Reyezuelo sencillo",
  "Remiz consobrinus": "Pájaro moscón chino",
  "Remiz coronatus": "Pájaro moscón coronado",
  "Remiz macronyx": "Pájaro moscón cabecinegro",
  "Remiz pendulinus": "Pájaro moscón europeo",
  "Rhipidura albicollis": "Abanico gorjiblanco",
  "Rhipidura aureola": "Abanico cejiblanco",
  "Rhipidura nigritorquis": "Abanico pío de Filipinas",
  "Rhodopechys sanguineus": "Camachuelo alirrojo asiático",
  "Rhodospiza obsoleta": "Camachuelo desertícola",
  "Rhodostethia rosea": "Gaviota rosada",
  "Rhopophilus albosuperciliaris": "Timalí del Tarim",
  "Rhopophilus pekinensis": "Timalí pekinés",
  "Rhyticeros undulatus": "Cálao gorjinegro",
  "Riparia chinensis": "Avión paludícola asiático",
  "Riparia diluta": "Avión pálido",
  "Riparia riparia": "Avión zapador",
  "Rissa tridactyla": "Gaviota tridáctila",
  "Rostratula benghalensis": "Aguatero bengalí",
  "Rubigula flaviventris": "Bulbul crestinegro",
  "Sarcogyps calvus": "Buitre cabecirrojo",
  "Sarkidiornis melanotos": "Pato crestudo afroasiático",
  "Saroglossa spilopterus": "Estornino alipinto",
  "Sasia ochracea": "Carpinterito cejiblanco",
  "Saundersilarus saundersi": "Gaviota de Saunders",
  "Saxicola caprata": "Tarabilla pía",
  "Saxicola ferreus": "Tarabilla gris",
  "Saxicola insignis": "Tarabilla de Hodgson",
  "Saxicola jerdoni": "Tarabilla de Jerdon",
  "Saxicola maurus": "Tarabilla Siberiana",
  "Saxicola rubetra": "Tarabilla norteña",
  "Saxicola stejnegeri": "Tarabilla del Amur",
  "Schoeniparus brunneus": "Fulveta de Gould",
  "Schoeniparus castaneceps": "Fulveta alirrufa",
  "Schoeniparus cinereus": "Fulveta goligualda",
  "Schoeniparus dubius": "Fulveta coronirrufa",
  "Schoeniparus rufogularis": "Fulveta gorjirrufa",
  "Schoeniparus variegaticeps": "Fulveta frentigualda",
  "Scolopax rusticola": "Chocha perdiz",
  "Serilophus lunatus": "Eurilaimo pechoplata",
  "Serilophus rubropygius": "Eurilaimo cejigrís",
  "Serinus pusillus": "Serín frentirrojo",
  "Sibirionetta formosa": "Cerceta del Baikal",
  "Sitta cinnamoventris": "Trepador ventricastaño",
  "Sitta europaea": "Trepador azul",
  "Sitta formosa": "Trepador hermoso",
  "Sitta frontalis": "Trepador piquirrojo",
  "Sitta himalayensis": "Trepador del Himalaya",
  "Sitta magna": "Trepador gigante",
  "Sitta nagaensis": "Trepador de las Naga",
  "Sitta przewalskii": "Trepador de Przewalski",
  "Sitta solangiae": "Trepador piquigualdo",
  "Sitta villosa": "Trepador chino",
  "Sitta yunnanensis": "Trepador de Yunnan",
  "Sittiparus castaneoventris": "Carbonero ventricastaño",
  "Sittiparus varius": "Carbonero variado",
  "Spatula clypeata": "Cuchara común",
  "Spatula querquedula": "Cerceta carretona",
  "Spelaeornis badeigularis": "Ratina mishmi",
  "Spelaeornis kinneari": "Ratina gorjipálida",
  "Spelaeornis reptatus": "Ratina ventrigrís",
  "Spelaeornis troglodytoides": "Ratina alibarrada",
  "Spilopelia chinensis": "Tórtola moteada oriental",
  "Spilopelia senegalensis": "Tórtola senegalesa",
  "Spilornis cheela": "Culebrera chiíla",
  "Spinus spinus": "Jilguero lúgano",
  "Spinus thibetanus": "Jilguero tibetano",
  "Spizixos canifrons": "Bulbul picogrueso",
  "Spizixos semitorques": "Bulbul collarejo",
  "Spodiopsar cineraceus": "Estornino gris",
  "Spodiopsar sericeus": "Estornino piquirrojo",
  "Stachyris humei": "Ratina picocuña occidental",
  "Stachyris nigriceps": "Timalí gorjigrís",
  "Stachyris nonggangensis": "Timalí de Nonggang",
  "Stachyris roberti": "Ratina picocuña oriental",
  "Stachyris strialata": "Timalí gorjipinto",
  "Staphida castaniceps": "Yuhina estriada",
  "Staphida torqueola": "Yuhina indochina",
  "Stercorarius longicaudus": "Págalo rabero",
  "Stercorarius maccormicki": "Págalo polar",
  "Stercorarius parasiticus": "Págalo parásito",
  "Stercorarius pomarinus": "Págalo pomarino",
  "Sterna acuticauda": "Charrán ventrinegro",
  "Sterna aurantia": "Charrán indio",
  "Sterna dougallii": "Charrán rosado",
  "Sterna hirundo": "Charrán común",
  "Sterna sumatrana": "Charrán de Sumatra",
  "Sternula albifrons": "Charrancito común",
  "Streptopelia decaocto": "Tórtola turca",
  "Streptopelia orientalis": "Tórtola oriental",
  "Streptopelia tranquebarica": "Tórtola cabecigrís",
  "Streptopelia turtur": "Tórtola europea",
  "Strix leptogrammica": "Cárabo oriental",
  "Strix nebulosa": "Cárabo lapón",
  "Strix nivicolum": "Cárabo del Himalaya",
  "Strix uralensis": "Cárabo uralense",
  "Sturnia malabarica": "Estornino malabar",
  "Sturnia pagodarum": "Estornino de las pagodas",
  "Sturnia sinensis": "Estornino chino",
  "Sturnus vulgaris": "Estornino pinto",
  "Sula dactylatra": "Piquero enmascarado",
  "Sula leucogaster": "Piquero pardo",
  "Sula sula": "Piquero patirrojo",
  "Surnia ulula": "Cárabo gavilán",
  "Surniculus lugubris": "Cuclillo drongo colitruncado",
  "Suthora alphonsiana": "Picoloro gorjigrís",
  "Suthora atrosuperciliaris": "Picoloro cejinegro",
  "Suthora brunnea": "Picoloro alipardo",
  "Suthora conspicillata": "Picoloro de anteojos",
  "Suthora davidiana": "Picoloro de David",
  "Suthora fulvifrons": "Picoloro leonado",
  "Suthora nipalensis": "Picoloro gorjinegro",
  "Suthora przewalskii": "Picoloro de Przewalski",
  "Suthora ricketti": "Picoloro de Yunnan",
  "Suthora verreauxi": "Picoloro dorado",
  "Suthora webbiana": "Picoloro de Webb",
  "Suthora zappeyi": "Picoloro encapuchado",
  "Sylvia atricapilla": "Curruca capirotada",
  "Sylviparus modestus": "Herrerillo modesto",
  "Synoicus chinensis": "Codorniz china",
  "Synthliboramphus antiquus": "Mérgulo antiguo",
  "Synthliboramphus wumizusume": "Mérgulo japonés",
  "Syrmaticus ellioti": "Faisán de Elliot",
  "Syrmaticus humiae": "Faisán de Hume",
  "Syrmaticus mikado": "Faisán mikado",
  "Syrmaticus reevesii": "Faisán venerado",
  "Syrrhaptes paradoxus": "Ganga de Pallas",
  "Syrrhaptes tibetanus": "Ganga tibetana",
  "Tachybaptus ruficollis": "Zampullín común",
  "Tachymarptis melba": "Vencejo real",
  "Tachyspiza badia": "Gavilán chikra",
  "Tachyspiza gularis": "Gavilancito japonés",
  "Tachyspiza soloensis": "Gavilán ranero",
  "Tachyspiza virgata": "Gavilán besra",
  "Tadorna cristata": "Tarro crestado",
  "Tadorna ferruginea": "Tarro canelo",
  "Tadorna tadorna": "Tarro blanco",
  "Taenioptynx brodiei": "Mochuelo acollarado",
  "Tarsiger chrysaeus": "Ruiseñor dorado",
  "Tarsiger cyanurus": "Ruiseñor coliazul",
  "Tarsiger hyperythrus": "Ruiseñor pechirrufo",
  "Tarsiger indicus": "Ruiseñor cejudo",
  "Tarsiger johnstoniae": "Ruiseñor de Formosa",
  "Tarsiger rufilatus": "Ruiseñor del Himalaya",
  "Temnurus temnurus": "Urraca de raquetas",
  "Tephrodornis virgatus": "Ceniciento grande",
  "Terpsiphone affinis": "Monarca del paraíso oriental",
  "Terpsiphone atrocaudata": "Monarca japonés",
  "Terpsiphone incei": "Monarca del paraíso chino",
  "Terpsiphone paradisi": "Monarca del paraíso indio",
  "Tesia cyaniventer": "Tesia cejiamarilla",
  "Tesia olivea": "Tesia pizarrosa",
  "Tetrao urogalloides": "Urogallo piquinegro",
  "Tetrao urogallus": "Urogallo común",
  "Tetraogallus altaicus": "Perdigallo altaico",
  "Tetraogallus himalayensis": "Perdigallo himalayo",
  "Tetraogallus tibetanus": "Perdigallo tibetano",
  "Tetraophasis obscurus": "Perdiz faisán gorjioscura",
  "Tetraophasis szechenyii": "Perdiz faisán gorjiclara",
  "Tetrastes bonasia": "Grévol común",
  "Tetrastes sewerzowi": "Grévol chino",
  "Tetrax tetrax": "Sisón común",
  "Thalasseus bengalensis": "Charrán bengalí",
  "Thalasseus bergii": "Charrán piquigualdo",
  "Thalasseus bernsteini": "Charrán chino",
  "Thalasseus sandvicensis": "Charrán patinegro",
  "Threskiornis melanocephalus": "Ibis oriental",
  "Tichodroma muraria": "Treparriscos",
  "Tickellia hodgsoni": "Mosquitero picoancho",
  "Timalia pileata": "Timalí capirotado",
  "Todiramphus chloris": "Alción acollarado",
  "Tragopan blythii": "Tragopán de Blyth",
  "Tragopan caboti": "Tragopán chino",
  "Tragopan melanocephalus": "Tragopán dorsigrís",
  "Tragopan satyra": "Tragopán sátiro",
  "Tragopan temminckii": "Tragopán cariazul",
  "Treron apicauda": "Vinago rabudo",
  "Treron bicinctus": "Vinago bicinta",
  "Treron curvirostra": "Vinago piquigrueso",
  "Treron formosae": "Vinago de Formosa",
  "Treron phayrei": "Vinago del Himalaya",
  "Treron phoenicopterus": "Vinago patigualdo",
  "Treron seimundi": "Vinago culigualdo",
  "Treron sieboldii": "Vinago japonés",
  "Treron sphenurus": "Vinago rabocuña",
  "Tringa brevipes": "Playero siberiano",
  "Tringa erythropus": "Archibebe oscuro",
  "Tringa flavipes": "Archibebe patigualdo chico",
  "Tringa glareola": "Andarríos bastardo",
  "Tringa guttifer": "Archibebe moteado",
  "Tringa incana": "Playero de Alaska",
  "Tringa nebularia": "Archibebe claro",
  "Tringa ochropus": "Andarríos grande",
  "Tringa stagnatilis": "Archibebe fino",
  "Tringa totanus": "Archibebe común",
  "Trochalopteron affine": "Charlatán carinegro",
  "Trochalopteron chrysopterum": "Charlatán de Assam",
  "Trochalopteron elliotii": "Charlatán de Elliot",
  "Trochalopteron erythrocephalum": "Charlatán coronicastaño",
  "Trochalopteron formosum": "Charlatán alirrojo",
  "Trochalopteron henrici": "Charlatán de Henri",
  "Trochalopteron imbricatum": "Charlatán de Bután",
  "Trochalopteron lineatum": "Charlatán barrado",
  "Trochalopteron melanostigma": "Charlatán orejiplateado",
  "Trochalopteron milnei": "Charlatán colirrojo",
  "Trochalopteron morrisonianum": "Charlatán de Morrison",
  "Trochalopteron squamatum": "Charlatán aliazul",
  "Trochalopteron subunicolor": "Charlatán modesto",
  "Trochalopteron variegatum": "Charlatán variegado",
  "Troglodytes troglodytes": "Chochín paleártico",
  "Tropicoperdix chloropus": "Arborófila pativerde",
  "Turdus albocinctus": "Mirlo acollarado",
  "Turdus atrogularis": "Zorzal papinegro",
  "Turdus boulboul": "Mirlo aligrís",
  "Turdus cardis": "Zorzal japonés",
  "Turdus chrysolaus": "Zorzal cabecipardo",
  "Turdus dissimilis": "Zorzal pechinegro",
  "Turdus eunomus": "Zorzal eunomo",
  "Turdus feae": "Zorzal de Fea",
  "Turdus hortulorum": "Zorzal dorsigrís",
  "Turdus iliacus": "Zorzal alirrojo",
  "Turdus kessleri": "Zorzal de Kessler",
  "Turdus mandarinus": "Mirlo mandarín",
  "Turdus maximus": "Mirlo del Himalaya",
  "Turdus merula": "Mirlo común",
  "Turdus migratorius": "Zorzal robín",
  "Turdus mupinensis": "Zorzal chino",
  "Turdus naumanni": "Zorzal de Naumann",
  "Turdus niveiceps": "Zorzal de Formosa",
  "Turdus obscurus": "Zorzal rojigrís",
  "Turdus pallidus": "Zorzal pálido",
  "Turdus philomelos": "Zorzal común",
  "Turdus pilaris": "Zorzal real",
  "Turdus rubrocanus": "Zorzal castaño",
  "Turdus ruficollis": "Zorzal papirrojo",
  "Turdus unicolor": "Zorzal unicolor",
  "Turdus viscivorus": "Zorzal charlo",
  "Turnix suscitator": "Torillo batallador",
  "Turnix sylvaticus": "Torillo andaluz",
  "Turnix tanki": "Torillo tanki",
  "Tyto longimembris": "Lechuza patilarga",
  "Upupa epops": "Abubilla común",
  "Uria aalge": "Arao común",
  "Urile pelagicus": "Cormorán pelágico",
  "Urile urile": "Cormorán carirrojo",
  "Urocissa caerulea": "Urraca de Formosa",
  "Urocissa erythroryncha": "Urraca piquirroja",
  "Urocissa flavirostris": "Urraca piquigualda",
  "Urocissa whiteheadi": "Urraca de Hainan",
  "Urocynchramus pylzowi": "Camachuelo de Przewalski",
  "Urosphena squameiceps": "Buscarla colicorta asiática",
  "Vanellus cinereus": "Avefría ceniza",
  "Vanellus duvaucelii": "Avefría fluvial",
  "Vanellus gregarius": "Avefría sociable",
  "Vanellus indicus": "Avefría india",
  "Vanellus leucurus": "Avefría coliblanca",
  "Vanellus vanellus": "Avefría europea",
  "Xema sabini": "Gaviota de Sabine",
  "Xenus cinereus": "Andarríos del Terek",
  "Yuhina bakeri": "Yuhina nuquiblanca",
  "Yuhina brunneiceps": "Yuhina de Formosa",
  "Yuhina flavicollis": "Yuhina bigotuda",
  "Yuhina gularis": "Yuhina goliestriada",
  "Yuhina nigrimenta": "Yuhina barbinegra",
  "Yuhina occipitalis": "Yuhina ventrirrufa",
  "Yungipicus canicapillus": "Pico crestigrís",
  "Yungipicus kizuki": "Pico kizuki",
  "Zapornia akool": "Gallineta akul",
  "Zapornia bicolor": "Polluela bicolor",
  "Zapornia fusca": "Polluela pechirrufa",
  "Zapornia parva": "Polluela bastarda",
  "Zapornia paykullii": "Polluela mandarina",
  "Zapornia pusilla": "Polluela chica",
  "Zonotrichia leucophrys": "Chingolo coroniblanco",
  "Zoothera aurea": "Zorzal dorado de Siberia",
  "Zoothera dauma": "Zorzal dorado del Himalaya",
  "Zoothera dixoni": "Zorzal de Dixon",
  "Zoothera griseiceps": "Zorzal dorsiliso de Sichuan",
  "Zoothera marginata": "Zorzal flanquioscuro",
  "Zoothera mollissima": "Zorzal dorsiliso del Himalaya",
  "Zoothera monticola": "Zorzal piquilargo",
  "Zoothera salimalii": "Zorzal de Salim Ali",
  "Zosterops erythropleurus": "Anteojitos flanquirrufo",
  "Zosterops japonicus": "Anteojitos japonés",
  "Zosterops meyeni": "Anteojitos filipino",
  "Zosterops palpebrosus": "Anteojitos oriental"
};
